# Generated by Django 4.2.5 on 2023-09-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='morceau',
            name='date_sortie',
            field=models.DateField(null=True),
        ),
    ]
