# Generated by Django 4.2.5 on 2023-09-27 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musiques', '0004_auto_20230926_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='morceau',
            name='interprete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='morceaux', to='musiques.artiste'),
        ),
    ]
