# Generated by Django 4.2.5 on 2023-09-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesTaches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='schedule_date',
        ),
    ]
