# Generated by Django 4.2.5 on 2023-09-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesTaches', '0002_remove_task_due_date_remove_task_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
